enum HttpCodeConstants {
    USER_SESSION_DOES_NOT_EXIST = 999,
    USER_INACTIVE = 996,
    NO_ROLE_ASSIGNED = 997,
    INVALID_TOKEN = 498,
    OK = 200,
    SUCCESS_CREATE = 201,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    INTERNAL_SERVER_ERROR = 500,
    CONFLICT = 409,
}

export default HttpCodeConstants
